server {
    listen 2025;
    server_name intranet.tek-it-izy.org;
    root /www/intranet;
    index index.html intranet.html;
    access_log /www/intranetlog/acces/access.log;
    error_log  /www/intranetlog/erreur/error.log;
    autoindex off;
    error_page 404 /pageserreurs/404.html;
    error_page 403 /pageserreurs/403.html;
    error_page 401 /pageserreurs/401.html;
    location /pageserreurs/ { root /www/intranet; internal; }
    auth_basic "Accès Intranet TEK-IT-IZY";
    auth_basic_user_file /etc/nginx/auth/.htpasswd_intranet;
    location ~ ^/~([^/]+)(/.*)?$ {
        alias /home/$1/pages_personnelles$2;
        index index.html intranet.html;
        autoindex off;
        auth_basic "Accès personnel";
        auth_basic_user_file /home/$1/.htpasswd;
    }
    location / { try_files $uri $uri/ =404; }
}
