server {
    listen 80;
    server_name www.tek-it-izy.org;
    root /www/public;
    index index.html accueil.html;
    access_log /www/log/acces/access.log;
    error_log  /www/log/erreur/error.log;
    autoindex on;
    error_page 404 /pageserreurs/404.html;
    error_page 403 /pageserreurs/403.html;
    location /pageserreurs/ { root /www; internal; }
    location / { try_files $uri $uri/ =404; }
}
